module.exports = {
  apps: [
    {
      name: 'systemzero-api',
      script: 'uvicorn',
      args: 'systemzero.interface.api.server:get_app --factory --host 0.0.0.0 --port 8000',
      cwd: '/opt/systemzero',
      interpreter: '/opt/systemzero/.venv/bin/python',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        PYTHONPATH: '/opt/systemzero',
        SZ_LOG_LEVEL: 'INFO',
        SZ_JSON_LOGS: 'true',
        SZ_LOG_PATH: '/opt/systemzero/logs/systemzero.log',
        SZ_ENABLE_HEALTH: 'true',
        SZ_ENABLE_METRICS: 'true',
        SZ_ENABLE_RATE_LIMITING: 'true',
        SZ_RATE_LIMIT_RPM: '100',
        SZ_RATE_LIMIT_BURST: '20',
        SZ_MAX_REQUEST_SIZE_MB: '10',
        SZ_API_KEYS_PATH: '/opt/systemzero/config/api_keys.yaml',
      },
      env_production: {
        PYTHONPATH: '/opt/systemzero',
        SZ_LOG_LEVEL: 'WARNING',
        SZ_JSON_LOGS: 'true',
        SZ_LOG_PATH: '/opt/systemzero/logs/systemzero.log',
        SZ_ENABLE_HEALTH: 'true',
        SZ_ENABLE_METRICS: 'true',
        SZ_ENABLE_RATE_LIMITING: 'true',
        SZ_RATE_LIMIT_RPM: '200',
        SZ_RATE_LIMIT_BURST: '40',
        SZ_MAX_REQUEST_SIZE_MB: '10',
        SZ_API_KEYS_PATH: '/opt/systemzero/config/api_keys.yaml',
      },
      error_file: '/opt/systemzero/logs/pm2-error.log',
      out_file: '/opt/systemzero/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 5,
    },
  ],
};
